name: Build, test and publish APK/AAB

env:
  main_project_module: app

  playstore_name: Dreamcatcher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug

      - name: Build apk release project (APK)
        run: ./gradlew assemble

      - name: Build app bundle release (AAB)
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.playstore_name }}-debug.apk
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.playstore_name }}-release-unsigned.apk
          path: ${{ env.main_project_module }}/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.playstore_name }}-release.aab
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/app-release.aab
